services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nagiyev05
      POSTGRES_DB: product_service

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    depends_on:
      - user-service
      - product-service
  
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    restart: always
    depends_on:
      - rabbitmq

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    restart: always
    depends_on:
      - postgres
      - rabbitmq
